# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: xxx@gmail.xom
author_name: xxx
has_binder: true
has_settings: false
kind: server
labextension_name: rerun-server
project_short_description: A JupyterLab extension.
python_name: rerun_server
repository: ''
test: false

